# Generated by Django 5.1.6 on 2025-06-22 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0004_comment_is_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursemember',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='coursemember',
            old_name='user_id',
            new_name='user',
        ),
    ]
