# Generated by Django 5.1.6 on 2025-06-22 16:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0005_rename_course_id_coursemember_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='release_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
