# Generated by Django 5.1.6 on 2025-06-23 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0006_coursecontent_release_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecontent',
            old_name='course_id',
            new_name='course',
        ),
    ]
