# Generated by Django 5.1.6 on 2025-06-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0007_rename_course_id_coursecontent_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='max_enrollments',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
