# Generated by Django 5.1.6 on 2025-06-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0008_course_max_enrollments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='max_enrollments',
            field=models.PositiveIntegerField(default=9),
        ),
    ]
