# Generated by Django 5.1.6 on 2025-06-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0009_alter_course_max_enrollments'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='max_students',
            field=models.IntegerField(default=50),
        ),
    ]
