# Generated by Django 5.1.6 on 2025-06-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0010_course_max_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='max_participants',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='max_students',
            field=models.IntegerField(default=10),
        ),
    ]
