# Generated by Django 5.1.6 on 2025-06-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0012_contentcompletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='max_participants',
            field=models.IntegerField(default=5),
        ),
    ]
